# Generated by Django 3.1.2 on 2020-10-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201019_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
