# Generated by Django 3.1.2 on 2020-10-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
    ]
